In [1]:
#PART1-DATA PREPROCESSING

# importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#importing dataset
dataset=pd.read_csv('Churn_Modelling.csv')
X=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13].values

# Encoding categorical variables
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X_1=LabelEncoder()
X[:,1]=labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2=LabelEncoder()
X[:,2]=labelencoder_X_2.fit_transform(X[:,2])
onehotencoder=OneHotEncoder(categorical_features=[1])
X=onehotencoder.fit_transform(X).toarray()
X=X[:,1:]

#spliting the dataset into training and test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)



C:\Users\NIKHIL\Anaconda3\envs\keras\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\NIKHIL\Anaconda3\envs\keras\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [2]:
X_train


array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [3]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [4]:
# Intialising the ANN
classifier=Sequential()

In [6]:
#Adding the input layer and first layer
classifier.add(Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform"))

In [7]:
#Adding the  second layer
classifier.add(Dense(activation="relu", units=6, kernel_initializer="uniform"))

In [8]:
#Adding the output layer
classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

In [9]:
#Compiling the ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [12]:
#Fitting the ANN to training dataset
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
8000/8000 [==============================] - 4s 524us/step - loss: 0.4000 - acc: 0.8357
Epoch 2/100
8000/8000 [==============================] - 4s 521us/step - loss: 0.3998 - acc: 0.8346
Epoch 3/100
8000/8000 [==============================] - 4s 540us/step - loss: 0.3999 - acc: 0.8359
Epoch 4/100
8000/8000 [==============================] - 4s 525us/step - loss: 0.3998 - acc: 0.8351
Epoch 5/100
8000/8000 [==============================] - 4s 537us/step - loss: 0.3998 - acc: 0.8347
Epoch 6/100
8000/8000 [==============================] - 4s 542us/step - loss: 0.3999 - acc: 0.8334
Epoch 7/100
8000/8000 [==============================] - 4s 559us/step - loss: 0.3998 - acc: 0.8352
Epoch 8/100
8000/8000 [==============================] - 4s 530us/step - loss: 0.3998 - acc: 0.8339
Epoch 9/100
8000/8000 [==============================] - 5s 585us/step - loss: 0.4000 - acc: 0.8355
Epoch 10/100
8000/8000 [==============================] - 5s 609us/step - loss: 0.3996 - acc: 0.8357

8000/8000 [==============================] - 5s 563us/step - loss: 0.3992 - acc: 0.8359
Epoch 83/100
8000/8000 [==============================] - 5s 615us/step - loss: 0.3995 - acc: 0.8341
Epoch 84/100
8000/8000 [==============================] - 5s 660us/step - loss: 0.3992 - acc: 0.8345
Epoch 85/100
8000/8000 [==============================] - 4s 538us/step - loss: 0.3992 - acc: 0.8345
Epoch 86/100
8000/8000 [==============================] - 4s 552us/step - loss: 0.3994 - acc: 0.8346
Epoch 87/100
8000/8000 [==============================] - 5s 617us/step - loss: 0.3989 - acc: 0.8372
Epoch 88/100
8000/8000 [==============================] - 4s 534us/step - loss: 0.3991 - acc: 0.8359
Epoch 89/100
8000/8000 [==============================] - 5s 581us/step - loss: 0.3996 - acc: 0.8355
Epoch 90/100
8000/8000 [==============================] - 5s 583us/step - loss: 0.3994 - acc: 0.8362
Epoch 91/100
8000/8000 [==============================] - 5s 578us/step - loss: 0.3993 - acc: 0.8347
Epo

In [13]:
#PART-3 MAKING PREDICTION AND EVALUATING

#Predict the test data results

y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)

In [14]:
y_pred


array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [15]:
#Making confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [16]:
cm


array([[1543,   52],
       [ 264,  141]], dtype=int64)

In [17]:
(1543+141)/2000


0.842

#homework trial


In [18]:
X_test

array([[ 1.75486502, -0.57369368, -0.55204276, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 , -0.57369368, -1.31490297, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 ,  1.74309049,  0.57162971, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-0.5698444 ,  1.74309049, -0.74791227, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -0.57369368, -0.00566991, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -0.57369368, -0.79945688, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [2]:
#PART 4 -EVALUATING ,IMPROVING AND TUNING THE MODEL(PERFROM AFTER 1ST PART NO NEED OF 2ND AND 3RD PART)

In [8]:
#Evaluating the ANN
import tensorflow-gpu
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
def build_classifier():
    classifier=Sequential();
    classifier.add(Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform"))
    classifier.add(Dense(activation="relu", units=6, kernel_initializer="uniform"))
    classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))
    classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return classifier
classifier=KerasClassifier(build_fn=build_classifier,batch_size=10,epochs=100)
accuracies=cross_val_score(estimator=classifier,X=X_train,y=y_train,cv=10,n_jobs=-1,error_score='raise')

SyntaxError: invalid syntax (<ipython-input-8-3395a2c19eb1>, line 2)